export default TYPES = {
  /* AUTH */
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  FORGOT_PW_SUCCESS: 'FORGOT_PW_SUCCESS',
  CHANGE_PW_SUCCESS: 'CHANGE_PW_SUCCESS',
  AUTH_DEVICE_INFO: 'AUTH_DEVICE_INFO',
  LOCATION_ALLOW_OK: 'LOCATION_ALLOW_OK',

  RESET_LOGIN_FORM: 'RESET_LOGIN_FORM',
  UPDATE_LOGIN_FORM: 'UPDATE_LOGIN_FORM',

  /* REG */
  RESET_REG_FORM: 'RESET_REG_FORM',
  UPDATE_REG_FORM: 'UPDATE_REG_FORM',

  /* CLIENTS */
  GET_CLIENT_PERSONAL_INFO_OK: 'GET_CLIENT_PERSONAL_INFO_OK',
  GET_CLIENT_SAVED_RECORDS_OK: 'GET_CLIENT_SAVED_RECORDS_OK',
  LIST_APICODES_LOAD: 'LIST_APICODES_LOAD',
  LIST_APICODES_OK: 'LIST_APICODES_OK',
  LIST_TRANSACTIONS_LOAD: 'LIST_TRANSACTIONS_LOAD',
  LIST_TRANSACTIONS_OK: 'LIST_TRANSACTIONS_OK',

  /* CAMPAIGNS */
  LIST_CAMPAIGNS_LOAD: 'LIST_CAMPAIGNS_LOAD',
  LIST_CAMPAIGNS_OK: 'LIST_CAMPAIGNS_OK',
  LIST_CAMPAIGNS_FAILED: 'LIST_CAMPAIGNS_FAILED',
  LIST_CAMPAIGNS_UPDATE_OK: 'LIST_CAMPAIGNS_UPDATE_OK',

  GET_CAMPAIGN_LOAD: 'GET_CAMPAIGN_LOAD',
  GET_CAMPAIGN_OK: 'GET_CAMPAIGN_OK',
  GET_CAMPAIGN_FAILED: 'GET_CAMPAIGN_FAILED',

  SEARCH_CAMPAIGN_OK: 'SEARCH_CAMPAIGN_OK',
  SEND_CAMPAIGN_SUCCESS: 'SEND_CAMPAIGN_SUCCESS',
  DELETE_CAMPAIGN_FAILED: 'DELETE_CAMPAIGN_FAILED',

  RESET_CAMPAIGN_FORM: 'RESET_CAMPAIGN_FORM',
  UPDATE_CAMPAIGN_FORM: 'UPDATE_CAMPAIGN_FORM',

  LIST_CAMPAIGN_TEMPLATES_LOAD: 'LIST_CAMPAIGNTEMPLATES_LOAD',
  LIST_CAMPAIGN_TEMPLATES_OK: 'LIST_CAMPAIGNTEMPLATES_OK',
  LIST_CAMPAIGN_TEMPLATES_FAILED: 'LIST_CAMPAIGNS_FAILED',
  LIST_CAMPAIGN_TEMPLATES_UPDATE_OK: 'LIST_CAMPAIGN_TEMPLATES_UPDATE_OK',

  LIST_CAMPAIGN_RECIPIENTS_LOAD: 'LIST_CAMPAIGNRECIPIENTS_LOAD',
  LIST_CAMPAIGN_RECIPIENTS_OK: 'LIST_CAMPAIGNRECIPIENTS_OK',
  LIST_CAMPAIGN_RECIPIENTS_FAILED: 'LIST_CAMPAIGNS_FAILED',
  LIST_CAMPAIGN_RECIPIENTS_UPDATE_OK: 'LIST_CAMPAIGN_RECIPIENTS_UPDATE_OK',

  /* DASHBOARD */
  GET_TODAYS_CAMPAIGN_OK: 'GET_TODAYS_CAMPAIGN_OK',
  GET_TODAYS_CAMPAIGN_FAILED: 'GET_TODAYS_CAMPAIGN_FAILED',
  GET_CAMPAIGN_CHART_OK: 'GET_CAMPAIGN_CHART_OK',
  GET_CAMPAIGN_CHART_FAILED: 'GET_CAMPAIGN_CHART_FAILED',

  /* DIRECTORIES */
  LIST_DIRECTORIES_LOAD: 'LIST_DIRECTORIES_LOAD',
  LIST_DIRECTORIES_OK: 'LIST_DIRECTORIES_OK',
  LIST_DIRECTORIES_FAILED: 'LIST_DIRECTORIES_FAILED',
  LIST_DIRECTORIES_UPDATE_OK: 'LIST_DIRECTORIES_UPDATE_OK',

  LIST_ALL_DIRECTORIES_OK: 'LIST_ALL_DIRECTORIES_OK',
  LIST_ALL_DIRECTORIES_FAILED: 'LIST_ALL_DIRECTORIES_FAILED',

  GET_DIRECTORY_LOAD: 'GET_DIRECTORY_LOAD',
  GET_DIRECTORY_OK: 'GET_DIRECTORY_OK',
  GET_DIRECTORY_FAILED: 'GET_DIRECTORY_FAILED',

  SEARCH_DIRECTORY_OK: 'SEARCH_DIRECTORY_OK',
  ADD_DIRECTORY_SUCCESS: 'ADD_DIRECTORY_SUCCESS',
  EDIT_DIRECTORY_SUCCESS: 'EDIT_DIRECTORY_SUCCESS',
  DELETE_DIRECTORY_FAILED: 'DELETE_DIRECTORY_FAILED',

  RESET_DIRECTORY_FORM: 'RESET_DIRECTORY_FORM',
  UPDATE_DIRECTORY_FORM: 'UPDATE_DIRECTORY_FORM',

  /* DIRECTORY CONTACTS */
  LIST_DIRECTORY_CONTACTS_LOAD: 'LIST_DIRECTORY_CONTACTS_LOAD',
  LIST_DIRECTORY_CONTACTS_OK: 'LIST_DIRECTORY_CONTACTS_OK',
  LIST_DIRECTORY_CONTACTS_FAILED: 'LIST_DIRECTORY_CONTACTS_FAILED',
  LIST_DIRECTORY_CONTACTS_UPDATE_OK: 'LIST_DIRECTORY_CONTACTS_UPDATE_OK',

  DELETE_DIRECTORY_CONTACTS_FAILED: 'DELETE_DIRECTORY_CONTACTS_FAILED',

  /* CONTACTS */
  LIST_CONTACTS_LOAD: 'LIST_CONTACTS_LOAD',
  LIST_CONTACTS_OK: 'LIST_CONTACTS_OK',
  LIST_CONTACTS_FAILED: 'LIST_CONTACTS_FAILED',

  GET_CONTACT_LOAD: 'GET_CONTACT_LOAD',
  GET_CONTACT_OK: 'GET_CONTACT_OK',
  GET_CONTACT_FAILED: 'GET_CONTACT_FAILED',

  SEARCH_CONTACT_OK: 'SEARCH_CONTACT_OK',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
  EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',
  DELETE_CONTACT_FAILED: 'DELETE_CONTACT_FAILED',

  RESET_CONTACT_FORM: 'RESET_CONTACT_FORM',
  UPDATE_CONTACT_FORM: 'UPDATE_CONTACT_FORM',

  /* PACKAGES */
  LIST_PACKAGES_LOAD: 'LIST_PACKAGES_LOAD',
  LIST_PACKAGES_OK: 'LIST_PACKAGES_OK',
  LIST_PACKAGES_FAILED: 'LIST_PACKAGES_FAILED',

  INCREASE_API_COUNT: 'INCREASE_API_COUNT',
  DECREASE_API_COUNT: 'DECREASE_API_COUNT',

  /* APICODES */
  GET_APICODE_CREDITS_LOAD: 'GET_APICODE_CREDITS_LOAD',
  GET_APICODE_CREDITS_OK: 'GET_APICODE_CREDITS_OK',
  GET_APICODE_CREDITS_FAILED: 'GET_APICODE_CREDITS_FAILED',

  GET_APICODE_CAMPAIGN_SUMMARY_LOAD: 'GET_APICODE_CAMPAIGN_SUMMARY_LOAD',
  GET_APICODE_CAMPAIGN_SUMMARY_OK: 'GET_APICODE_CAMPAIGN_SUMMARY_OK',
  GET_APICODE_CAMPAIGN_SUMMARY_FAILED: 'GET_APICODE_CAMPAIGN_SUMMARY_FAILED',

  TOP_UP_APICODE_CREDITS_SUCCESS: 'TOP_UP_APICODE_CREDITS_SUCCESS',
  TOP_UP_APICODE_CREDITS_FAILED: 'TOP_UP_APICODE_CREDITS_FAILED',

  /* TEMPLATES */
  LIST_TEMPLATES_LOAD: 'LIST_TEMPLATES_LOAD',
  LIST_TEMPLATES_OK: 'LIST_TEMPLATES_OK',
  LIST_TEMPLATES_FAILED: 'LIST_TEMPLATES_FAILED',
  LIST_TEMPLATES_UPDATE_OK: 'LIST_TEMPLATES_UPDATE_OK',

  GET_TEMPLATE_LOAD: 'GET_TEMPLATE_LOAD',
  GET_TEMPLATE_OK: 'GET_TEMPLATE_OK',
  GET_TEMPLATE_FAILED: 'GET_TEMPLATE_FAILED',

  SEARCH_TEMPLATE_OK: 'SEARCH_TEMPLATE_OK',
  DELETE_TEMPLATE_FAILED: 'DELETE_TEMPLATE_FAILED',

  RESET_TEMPLATE_FORM: 'RESET_TEMPLATE_FORM',
  UPDATE_TEMPLATE_FORM: 'UPDATE_TEMPLATE_FORM',

  /* ACCOUNT PROFILE */
  GET_ACCOUNT_LOAD: 'GET_ACCOUNT_LOAD',
  GET_ACCOUNT_OK: 'GET_ACCOUNT_OK',
  GET_ACCOUNT_FAILED: 'GET_ACCOUNT_FAILED',

  UPDATE_ACCOUNT_FORM: 'UPDATE_ACCOUNT_FORM',
  RESET_ACCOUNT_FORM: 'RESET_ACCOUNT_FORM',

  /* DEVICES */
  LIST_DEVICES_LOAD: 'LIST_DEVICES_LOAD',
  LIST_DEVICES_OK: 'LIST_DEVICES_OK',
  LIST_DEVICES_UPDATE_OK: 'LIST_DEVICES_UPDATE_OK',
  LIST_DEVICES_FAILED: 'LIST_DEVICES_FAILED',
  GET_DEVICE_LOAD: 'GET_DEVICE_LOAD',
  GET_DEVICE_OK: 'GET_DEVICE_OK',
  GET_DEVICE_FAILED: 'GET_DEVICE_FAILED',
};
